[build]
target = "target-specs.json"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"] 

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
